version: "3.8"
services:
  rest:
    build:
      context: .
    ports:
      - "6868:6868"
      - "5005:5005"
    environment:
      SERVER_PORT: 6868
      SPRING_DATA_MONGODB_HOST: kj-mongodb
      SPRING_DATA_MONGODB_PORT: 27777
  mongo:
    image: mongo
    container_name: kj-mongodb
    restart: always
    ports:
      - "27777:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: kj-mongodb
      ME_CONFIG_MONGODB_PORT: 27777
